CREATE TABLE refresh_tokens(
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    token UUID UNIQUE NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_to TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token_state VARCHAR(10) NOT NULL CHECK(token_state IN ('ACTIVE','REVOKED'))
);
